services:
  caserita-business-logic:
    container_name: caserita-business-logic
    image: caserita-business-logic-app-local:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development.local
    ports:
      - '3000:3000'
    volumes: []
    environment:
      - NODE_ENV=production
      - NATS_SERVERS=nats://nats-server
      - PORT=3000
      - TAX_IDENTITY_VALIDATION_BASE_URL=http://caserita-taxidentityvalidation-ms:3001/taxidentityvalidations
    networks:
      - caserita-network-ecosystem

networks:
  caserita-network-ecosystem:
    external: true
